### ISSUE TITLE
mobile menu

### ISSUE THREAD

**Issue by markendley** [markendley/ftrnghp#16]

**Comment by markendley** [comment]
Hey mate, I like what you've done but can we make it like the menu on my website? I'll update the psd if needed. 
See image below..

![screen shot 2018-03-26 at 2 00 03 pm](https://user-images.githubusercontent.com/6570606/37902496-52512eaa-3140-11e8-8f01-03cd72a51183.png)

**Comment by markendley** [comment]
(this is his site

https://conceptanddesign.com.au/

)

**Comment by ugurcanbulut** [comment]
Fixed!
