### ISSUE TITLE
footer redesign

### ISSUE THREAD

**Issue by markendley** [markendley/ftrnghp#17]
After seeing the footer how I designed it I think it looks a little weird.. Can we maybe try making the whole thing fully responsive and adding another column with the services they provide? Please see rough mock up attached

![screen shot 2018-03-26 at 2 14 28 pm](https://user-images.githubusercontent.com/6570606/37902581-9343a8e8-3140-11e8-80eb-0b0d0b95651e.png)

**Comment by ugurcanbulut** [comment]
Done!
